# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: Saravanan-test-agent

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar-code-analyser'
    organization: 'saravanansaravanan'
    scannerMode: 'Other'
- task: Maven@4
  inputs:
    mavenPomFile: 'JtProject/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
    checkStyleRunAnalysis: true
    pmdRunAnalysis: true
    findBugsRunAnalysis: true
    spotBugsRunAnalysis: true

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-TestSuite.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)\target\surefire-reports\old'
    publishRunAttachments: true

- task: CopyFiles@2
  inputs:
    Contents: '**/*jar'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


