# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: Saravanan-test-agent

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SonarQube_azuredevops'
    scannerMode: 'MSBuild'
    projectKey: 'd75737d586419b9f53f58ea8fbb32c7d3f91ec0b'
    projectName: 'Azure-devops'

- task: Maven@4
  inputs:
    mavenPomFile: 'JtProject/pom.xml'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false


- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-TestSuite.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)\target\surefire-reports\old'
    publishRunAttachments: true

- task: CopyFiles@2
  inputs:
    Contents: '**/*jar'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


